#!/bin/sh
#
# Copyright (c) 1997 The President and Fellows of Harvard College.
# All rights reserved.
# Copyright (c) 1997 Aaron B. Brown.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program, in the file COPYING in this distribution;
#   if not, write to the Free Software Foundation, Inc., 675 Mass Ave,
#   Cambridge, MA 02139, USA.
#
# Results obtained from this benchmark may be published only under the
# name "HBench-OS".

#
# create-all-analyses
#
# This script is meant to be run from the results directory. It looks at
# all directories that are two levels deep (i.e., */*) and runs gen-analysis
# on them.
#
# $Id: create-all-analyses,v 1.3 1997/06/27 00:36:21 abrown Exp $

# Step 1: Discover hbench root path
HBENCHROOT=`(cd \`dirname $0\`/.. ; pwd)`

for dir in */*
do
    if [ -d $dir ]; then
	echo "Running analysis on $dir..."
	${HBENCHROOT}/scripts/gen-analysis $dir > ${dir}/analysis
    fi
done
